Skip notifications when OCR mode is "skip file"
R0Wi-DEV/workflow_ocr pull request #233
Opened 2023-10-03 18:46 UTC by R0Wi

* Fixes #232
* Move logic to OcrService

2023-10-04 09:47 UTC, bahnwaerter requested changes
Thanks @R0Wi for refactoring the OCR notification. The refactoring looks good to me. So feel free to merge your code changes after considering my two small comments.

2023-10-04 09:47 UTC, bahnwaerter commented on tests/Unit/Service/OcrServiceTest.php
> +	// }
Please remove unused code fragments.

```suggestion
```

2023-10-04 09:47 UTC, bahnwaerter commented on lib/Service/IOcrService.php
> +	 * @param string $uid 					The id of the user who has access to this file
Please preserve indentation from existing parameter description below.

2023-10-05 07:19 UTC, R0Wi commented
Thanks for the heads up @bahnwaerter 👍

2023-10-05 07:28 UTC, merged